### PR TITLE
Update trakt.py

### PR DESCRIPTION
**Pull request by kasi45**
typo

### CODE REVIEW

**Comment by 123Venom** [comment]
that module was for future use that's not called as of yet but I'll fix the oopsie for the day I get round to calling that thing.  Thanks

**Comment by jaimsitecom** [comment]
is there a connection to the recent trakt or tvdb issue why the tv show SURVIVOR can't be added onto the kodi library?  it's really weird that it's the only show that whenever i try to add SURVIVOR by 'add to library', Venom hangs and then crashes...

**Comment by 123Venom** [comment]
> 
> 
> is there a connection to the recent trakt or tvdb issue why the tv show SURVIVOR can't be added onto the kodi library? it's really weird that it's the only show that whenever i try to add SURVIVOR by 'add to library', Venom hangs and then crashes...

Boy I'll tell ya I just spent the last 6hrs logging and tracking this annoying issue.  People refer to it as an exo fork Survivor bug but that may have been true at one time but what I discovered the cause to be is puzzling.  I logged the entire code start to finish to track it, no quick task.  It breaks right at the point where my actor profile pics are, which no exo fork does so it's puzzling how it's refered to as that,  yet they all load and the code does not have an error.  I'm venturing a guess that this show reports 576 actor profiles in the tvdb "actors.xml" response.  I don't know if that amount of data is what breaks it for this one show but when I commented out the whole actors section it works fine.  It's very odd behavior, even through a few memory issue erros so this has to have overloaded it in some way.  I'm going to test a check for this one show and void the setting of actor profile info and pics to see if we can live with that.  Beyond that I'm not removing all the actor profile work I did.  There was a post on reddit bout this and I want to post my findings to see if any other dev has some input on it.  Was that your post?  I can't find it now

**Comment by jaimsitecom** [comment]
Thanks for confirming this weird ‘quirk’. I was goin crazy trying to figure out if it is my setting of folders or whatever that causes the crash. 

Anyways, that wasnt my reddit post. Must be someboy else’s. 

Thanks again

**Comment by 123Venom** [comment]
Finally found the a4k post I was digging for.  Little more info on the issue that caused this problem I posted there. [https://www.reddit.com/r/Addons4Kodi/comments/drg0d6/still_able_to_download_from_exodus_redux/](url) .

**Comment by jaimsitecom** [comment]
Hi, noticed errors when adding tv shows (specifically V-Wars, and Crisis aftermath) When i go Try to see the episodes in their folder, it just has a popup saying “SEASONS, Nothing was found”.

Ty

On Dec 3, 2019, at 3:24 AM, 123Venom <notifications@github.com> wrote:

﻿

Finally found the a4k post I was digging for. Little more info on the issue that caused this problem I posted there. https://www.reddit.com/r/Addons4Kodi/comments/drg0d6/still_able_to_download_from_exodus_redux/<url> .

**Comment by jaimsitecom** [comment]
I also had to go back to v3.5.5 coz the auto library update at startup disappeared on the latest one v3.5.7. 

I like the old version better for my needs. Simple but effective. Ty

**Comment by 123Venom** [comment]
should be squared away now in v3.4.0

**Pull request closed without merging**
