### PR TITLE
remove unused setting id from userdata setting file

### PR DESCRIPTION
**Pull request by rrosajp**
clean_setting() will get Default setting file ,setting Id and compare with userdata setting Id if not found in default then it will remove the same.

### CODE REVIEW

**Comment by rrosajp** [comment]
if u like to used as service when addon update then i can add to service.py let me know.

**Comment by bjbca** [comment]
👍

**Comment by 123Venom** [comment]
Unfortunately this came a little late.  I've already completed a modified version of a function that's been floating around, slowly making it's way into exo forks. It uses Elemtree instead and works pretty good at removing old deprecated settings from userdata settings.xml.  I believe it came from FEN. I set it up to auto run **only** upon a new version update.  That way in the event I've removed any setting no longer used the function will now remove those deprecated settings from the userdata settings.xml.  The notification actually reports the number of deprecated entries removed vs. just "Setting file clened"...lol....I just noticed my copy/paste from your lang file and ya missed the "a" in cleaned.
```
def clean_settings():
	import xml.etree.ElementTree as ET
	def _make_content(dict_object):
		content = '<settings version="2">'
		for item in dict_object:
			if item['id'] in active_settings:
				if 'default' in item and 'value' in item: content += '\n    <setting id="%s" default="%s">%s</setting>' % (item['id'], item['default'], item['value'])
				elif 'default' in item: content += '\n    <setting id="%s" default="%s"></setting>' % (item['id'], item['default'])
				elif 'value' in item: content += '\n    <setting id="%s">%s</setting>' % (item['id'], item['value'])
				else: content += '\n    <setting id="%s"></setting>'
			else: removed_settings.append(item)
		content += '\n</settings>'
		return content
	try:
		removed_settings = []
		active_settings = []
		current_user_settings = []
		addon = xbmcaddon.Addon(id= 'plugin.video.venom')
		addon_dir = xbmc.translatePath(addon.getAddonInfo('path'))
		profile_dir = xbmc.translatePath(addon.getAddonInfo('profile'))
		active_settings_xml = os.path.join(addon_dir, 'resources', 'settings.xml')
		root = ET.parse(active_settings_xml).getroot()
		for item in root.findall('./category/setting'):
			setting_id = item.get('id')
			if setting_id: active_settings.append(setting_id)
		settings_xml = os.path.join(profile_dir, 'settings.xml')
		root = ET.parse(settings_xml).getroot()
		for item in root:
			dict_item = {}
			setting_id = item.get('id')
			setting_default = item.get('default')
			setting_value = item.text
			dict_item['id'] = setting_id
			if setting_value: dict_item['value'] = setting_value
			if setting_default: dict_item['default'] = setting_default
			current_user_settings.append(dict_item)
		new_content = _make_content(current_user_settings)
		nfo_file = xbmcvfs.File(settings_xml, 'w')
		nfo_file.write(new_content)
		nfo_file.close()
		sleep(200)
		infoDialog(lang(32084).encode('utf-8').format(str(len(removed_settings))))
	except:
		import traceback
		traceback.print_exc()
		infoDialog('Error Cleaning Settings.xml. Old settings.xml files Restored.')```

**Comment by 123Venom** [comment]
@rrosajp remember that discussion we had about escape characters in settings.xml?  Well as fait would have it Kodi isn't bothered by not using them here but ElementTree fails without them in use in an xml you parse, so I had to modify that to work..lol

**Comment by 123Venom** [comment]
This works better.  I added the ability to also remove deprecated settings from OpenScrapers...first run reported 135...yikes.  OpenScrapers had allot of scrapers added and removed over time!  I also changed the infoDialog() to notification() because infoDialog() hard codes the addonInfo('name') while notification() gives control over the title so now the notification states "Venom" or "OpenScrapers Module".   OpenScrapers setting.xml also is not using escape characters so it initially failed using ElementTree till I spotted that and fixed it so an update there is needed for this as well

```
def clean_settings():
	import xml.etree.ElementTree as ET
	def _make_content(dict_object):
		content = '<settings version="2">'
		for item in dict_object:
			if item['id'] in active_settings:
				if 'default' in item and 'value' in item: content += '\n    <setting id="%s" default="%s">%s</setting>' % (item['id'], item['default'], item['value'])
				elif 'default' in item: content += '\n    <setting id="%s" default="%s"></setting>' % (item['id'], item['default'])
				elif 'value' in item: content += '\n    <setting id="%s">%s</setting>' % (item['id'], item['value'])
				else: content += '\n    <setting id="%s"></setting>'
			else: removed_settings.append(item)
		content += '\n</settings>'
		return content

	for addon_id in ('plugin.video.venom', 'script.module.openscrapers'):
		try:
			removed_settings = []
			active_settings = []
			current_user_settings = []
			addon = xbmcaddon.Addon(id=addon_id)
			addon_name = addon.getAddonInfo('name')
			addon_dir = xbmc.translatePath(addon.getAddonInfo('path'))
			profile_dir = xbmc.translatePath(addon.getAddonInfo('profile'))
			active_settings_xml = os.path.join(addon_dir, 'resources', 'settings.xml')
			root = ET.parse(active_settings_xml).getroot()
			for item in root.findall('./category/setting'):
				setting_id = item.get('id')
				if setting_id: active_settings.append(setting_id)
			settings_xml = os.path.join(profile_dir, 'settings.xml')
			root = ET.parse(settings_xml).getroot()
			for item in root:
				dict_item = {}
				setting_id = item.get('id')
				setting_default = item.get('default')
				setting_value = item.text
				dict_item['id'] = setting_id
				if setting_value: dict_item['value'] = setting_value
				if setting_default: dict_item['default'] = setting_default
				current_user_settings.append(dict_item)
			new_content = _make_content(current_user_settings)
			nfo_file = xbmcvfs.File(settings_xml, 'w')
			nfo_file.write(new_content)
			nfo_file.close()
			sleep(200)
			notification(title = addon_name, message = lang(32084).encode('utf-8').format(str(len(removed_settings))), icon = 'INFO', sound=False)
		except:
			import traceback
			traceback.print_exc()
			notification(title = addon_name, message = 'Error Cleaning Settings.xml. Old settings.xml files Restored.', icon = 'INFO', sound=False)```

**Comment by host505** [comment]
> I also changed the infoDialog() to notification() because infoDialog() hard codes the addonInfo('name') while notification() gives control over the title so now the notification states "Venom" or "OpenScrapers Module". 

You can change the heading on infoDialog() as well, since you defined addon_name you can
`infoDialog(lang(32084).encode('utf-8').format(str(len(removed_settings))), heading=addon_name)`

**Comment by rrosajp** [comment]
@123Venom  yeah i remember that pull request for escape characters in settings.xml, btw yeah i see 'a' is missing hahaha. thanks for notice.

**Comment by 123Venom** [comment]
> 
> 
> > I also changed the infoDialog() to notification() because infoDialog() hard codes the addonInfo('name') while notification() gives control over the title so now the notification states "Venom" or "OpenScrapers Module".
> 
> You can change the heading on infoDialog() as well, since you defined addon_name you can
> `infoDialog(lang(32084).encode('utf-8').format(str(len(removed_settings))), heading=addon_name)`

you are right...I forgot about that and shot from memory because I seldom ever use infoDialog() anymore.  I had written a new notification that was little easier to deal with and isinstance() to check what you're passing it.

If we're really getting picky did you spot I moved the `try:` block start?  If it's before the `for` loop and your first addon_id throws an exception it will not continue for the next addon_id so the loop terminates first exception...after the for loop it will continue.

**Comment by jewbmx** [comment]
Dont know if any of ya guys have the same issue but i tried these features out last night/this morning and the version host505 used with the ET use gave me errors no matter how i modified it. I swapped it all out for the version here using BS and it works fine and fast. Only downfall i seen was the default tag gets moved to the front and id goes to the end lol.

I dont really like BS but ET always seems to be a stubborn fucker lol atleast for me and my droid.

Also should thank yall for the code and this lil convo i seen :) thanks to this my settings file is cut in half and i feel alot cleaner lmao

**Comment by 123Venom** [comment]
ET gives errors when it tries to parse an xml and the expected criteria is not met.  Here's what usually hoses it...make sure you use escape characters.  Kodi does not care if you use a simple `&` in a settings.xml but ET freaks out and throws an error unless you use `&amp;`.  First time I dialed in that code it sure took a shit on me to with errors.  If you use traceback in your exception it will report the line number and my bet says your settings.xml has something ET expects conformance to xml standards and technically speaking escape characters are correct but kodi doesn't care so some of use fail to use them in settings.xml..me included till this ET thingy.  Use try and except blocks with traceback in the exception and you'll capture every line error it sees in the xml.  Check that!  I used ET to parse actors.xml from TVDB and honestly it really is the shitz and makes parsing xml's a breeze.

**Comment by 123Venom** [comment]
notice I use traceback in the exception...if you just took the code as TikiPete had it's not there...add it to capture those errors ET throws but you won't see without using that.  Then you'll have the line number where the error exists.  Good luck..tell me if that finds the little booboos...worked for me finding them and fixing them to satisfy ET.

**Comment by 123Venom** [comment]
and I had the errors in both Venom and OpenScrapers so I had to fix both...all were escape character related issues...cured that and all was golden.  New version install and it auto runs and cleans that old depracted shit kodi refuses to remove.

**Comment by jewbmx** [comment]
Just opened my settings and it is a few missed &'s lol. Got 3 of em on newish settings i didnt notice em.

Didnt try to run the feature again but im guessing it'd go fine now. Been doing a little remodeling lately so the option to wipe out old settings is pretty damn handy lol

**Comment by 123Venom** [comment]
fucking plain `&` will fuck up ET every time!  It actually works real good and TikiPete did a nice job on that code.  First run on my test pc, that's a mess for my testing purposes only, cleaned 135 settings from OpenScrapers...lol...course scrapers we update so often it's no wonders settings removed so frequently with them and left behind.
Only other thing to watch for is if you use his code to clean more than just your addon, like a scraper pack, he has the `try:` before the `for loop` so if the first one fails the whole thing takes a shit.  Move the `try:` after the loop so if first fails it will loop to the next without breakage.

**Pull request closed without merging**
