### PR TITLE
Update strings.po

### PR DESCRIPTION
**Pull request by djdirty60**
Updated

### CODE REVIEW

**Comment by 123Venom** [comment]
Appreciate your work on this and I'll be the first to admit I've pretty much abandoned updating language .po files sadly.  There's one issue I see with the hard work you've put in.  A number of ids will no longer match up and that should be reviewed against the English translation file.  Here's an example that I spotted... `Remove CAM and SD sources` this is now separate settings in Venom and I'm not sure if that made it in the Dutch translation.  If it did great but I'll grantee many did not.  Not sure if you have the time to do that cross check also?

**Comment by 123Venom** [comment]
Also be careful removing leading whitespace.  That was intentional to indent it as it's part of a parent setting and makes it look better indented.
indent

**Comment by drinfernoo** [comment]
@123Venom You can use `subsetting="true"` to have Kodi do that for you 😉

**Comment by 123Venom** [comment]
> 
> 
> @123Venom You can use `subsetting="true"` to have Kodi do that for you 😉

Ahhh nice @drinfernoo ya know what...I've seen it done before and should have realized I could have gone back and changed those cases for that.

@djdirty60 on that note go ahead and remove the whitepsace.  I'll check see how many cases I need to use ``subsetting` for and switch them over.

**Comment by kodix85** [comment]
Hi,

I'm from Poland. When I activate Api  language into Polish, Venom does not translate the media titles/description.

Greetings.

**Comment by 123Venom** [comment]
I've reviewed the issue and confirmed it.  Unfortunately it appears during the last few re-writes done I've completely neglected translations.  I can not promise you if and when I'll ever get to this, it's extensive the amount of work it needs to bring it back to full functionality.  I'd suggesting using either Fen or The Oath as I've tested both and they support translations quite nicely.

**Pull request closed without merging**
